# RestriçÕes de quantidade de aulas, disciplinas e professores

# CARGA HORÁRIA
CARGA_HORARIA_MINUTOS = 50
CARGA_HORARIA_MAXIMA_DISCIPLINA = 6
CARGA_HORARIA_MINIMA_DISCIPLINA = 2
CARGA_HORARIA_MAXIMA_DISCIPLINA_POR_DIA = 4
CARGA_HORARIA_MAXIMA_PROFESSOR_SEMANA = 30
CARGA_HORARIA_MAXIMA_PROFESSOR_DIA = 6
CARGA_HORARIA_MAXIMA_PROFESSOR_DIA_POR_DISCIPLINA = 4

# QUANTIDADES
MAXIMO_DISCIPLINAS_POR_PROFESSOR = 3
MAXIMO_DIAS_DE_DISCIPLINA_POR_SEMANA = 2
